/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HealthRouteImport } from './routes/health'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ApiListenRouteImport } from './routes/api/listen'
import { Route as ApiMutateRouteImport } from './routes/api/mutate'
import { Route as ApiPresenceRouteImport } from './routes/api/presence'
import { Route as ApiSchemasRouteImport } from './routes/api/schemas'
import { Route as DebugLiveRouteImport } from './routes/debug/live'
import { Route as StructureIndexRouteImport } from './routes/structure/index'
import { Route as StructureSplatRouteImport } from './routes/structure/$'
import { Route as ApiBacklinksIdRouteImport } from './routes/api/backlinks/$id'
import { Route as ApiMediaIndexRouteImport } from './routes/api/media/index'
import { Route as ApiMediaUploadRouteImport } from './routes/api/media/upload'
import { Route as ApiQueryTypeRouteImport } from './routes/api/query/$type'
import { Route as ApiDocTypeIdRouteImport } from './routes/api/doc/$type/$id'
import { Route as ApiHistoryTypeIdRouteImport } from './routes/api/history/$type/$id'
import { Route as ApiMediaIdIndexRouteImport } from './routes/api/media/$id/index'
import { Route as ApiMediaIdUsageRouteImport } from './routes/api/media/$id/usage'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiListenRoute = ApiListenRouteImport.update({
  id: '/api/listen',
  path: '/api/listen',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMutateRoute = ApiMutateRouteImport.update({
  id: '/api/mutate',
  path: '/api/mutate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPresenceRoute = ApiPresenceRouteImport.update({
  id: '/api/presence',
  path: '/api/presence',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSchemasRoute = ApiSchemasRouteImport.update({
  id: '/api/schemas',
  path: '/api/schemas',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugLiveRoute = DebugLiveRouteImport.update({
  id: '/debug/live',
  path: '/debug/live',
  getParentRoute: () => rootRouteImport,
} as any)
const StructureIndexRoute = StructureIndexRouteImport.update({
  id: '/structure/',
  path: '/structure/',
  getParentRoute: () => rootRouteImport,
} as any)
const StructureSplatRoute = StructureSplatRouteImport.update({
  id: '/structure/$',
  path: '/structure/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBacklinksIdRoute = ApiBacklinksIdRouteImport.update({
  id: '/api/backlinks/$id',
  path: '/api/backlinks/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaIndexRoute = ApiMediaIndexRouteImport.update({
  id: '/api/media/',
  path: '/api/media/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaUploadRoute = ApiMediaUploadRouteImport.update({
  id: '/api/media/upload',
  path: '/api/media/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQueryTypeRoute = ApiQueryTypeRouteImport.update({
  id: '/api/query/$type',
  path: '/api/query/$type',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocTypeIdRoute = ApiDocTypeIdRouteImport.update({
  id: '/api/doc/$type/$id',
  path: '/api/doc/$type/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHistoryTypeIdRoute = ApiHistoryTypeIdRouteImport.update({
  id: '/api/history/$type/$id',
  path: '/api/history/$type/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaIdIndexRoute = ApiMediaIdIndexRouteImport.update({
  id: '/api/media/$id/',
  path: '/api/media/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaIdUsageRoute = ApiMediaIdUsageRouteImport.update({
  id: '/api/media/$id/usage',
  path: '/api/media/$id/usage',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/api/listen': typeof ApiListenRoute
  '/api/mutate': typeof ApiMutateRoute
  '/api/presence': typeof ApiPresenceRoute
  '/api/schemas': typeof ApiSchemasRoute
  '/debug/live': typeof DebugLiveRoute
  '/structure/$': typeof StructureSplatRoute
  '/structure/': typeof StructureIndexRoute
  '/api/backlinks/$id': typeof ApiBacklinksIdRoute
  '/api/media/upload': typeof ApiMediaUploadRoute
  '/api/query/$type': typeof ApiQueryTypeRoute
  '/api/media/': typeof ApiMediaIndexRoute
  '/api/doc/$type/$id': typeof ApiDocTypeIdRoute
  '/api/history/$type/$id': typeof ApiHistoryTypeIdRoute
  '/api/media/$id/usage': typeof ApiMediaIdUsageRoute
  '/api/media/$id/': typeof ApiMediaIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/api/listen': typeof ApiListenRoute
  '/api/mutate': typeof ApiMutateRoute
  '/api/presence': typeof ApiPresenceRoute
  '/api/schemas': typeof ApiSchemasRoute
  '/debug/live': typeof DebugLiveRoute
  '/structure/$': typeof StructureSplatRoute
  '/structure': typeof StructureIndexRoute
  '/api/backlinks/$id': typeof ApiBacklinksIdRoute
  '/api/media/upload': typeof ApiMediaUploadRoute
  '/api/query/$type': typeof ApiQueryTypeRoute
  '/api/media': typeof ApiMediaIndexRoute
  '/api/doc/$type/$id': typeof ApiDocTypeIdRoute
  '/api/history/$type/$id': typeof ApiHistoryTypeIdRoute
  '/api/media/$id/usage': typeof ApiMediaIdUsageRoute
  '/api/media/$id': typeof ApiMediaIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/api/listen': typeof ApiListenRoute
  '/api/mutate': typeof ApiMutateRoute
  '/api/presence': typeof ApiPresenceRoute
  '/api/schemas': typeof ApiSchemasRoute
  '/debug/live': typeof DebugLiveRoute
  '/structure/$': typeof StructureSplatRoute
  '/structure/': typeof StructureIndexRoute
  '/api/backlinks/$id': typeof ApiBacklinksIdRoute
  '/api/media/upload': typeof ApiMediaUploadRoute
  '/api/query/$type': typeof ApiQueryTypeRoute
  '/api/media/': typeof ApiMediaIndexRoute
  '/api/doc/$type/$id': typeof ApiDocTypeIdRoute
  '/api/history/$type/$id': typeof ApiHistoryTypeIdRoute
  '/api/media/$id/usage': typeof ApiMediaIdUsageRoute
  '/api/media/$id/': typeof ApiMediaIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/health'
    | '/login'
    | '/api/listen'
    | '/api/mutate'
    | '/api/presence'
    | '/api/schemas'
    | '/debug/live'
    | '/structure/$'
    | '/structure/'
    | '/api/backlinks/$id'
    | '/api/media/upload'
    | '/api/query/$type'
    | '/api/media/'
    | '/api/doc/$type/$id'
    | '/api/history/$type/$id'
    | '/api/media/$id/usage'
    | '/api/media/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/health'
    | '/login'
    | '/api/listen'
    | '/api/mutate'
    | '/api/presence'
    | '/api/schemas'
    | '/debug/live'
    | '/structure/$'
    | '/structure'
    | '/api/backlinks/$id'
    | '/api/media/upload'
    | '/api/query/$type'
    | '/api/media'
    | '/api/doc/$type/$id'
    | '/api/history/$type/$id'
    | '/api/media/$id/usage'
    | '/api/media/$id'
  id:
    | '__root__'
    | '/'
    | '/health'
    | '/login'
    | '/api/listen'
    | '/api/mutate'
    | '/api/presence'
    | '/api/schemas'
    | '/debug/live'
    | '/structure/$'
    | '/structure/'
    | '/api/backlinks/$id'
    | '/api/media/upload'
    | '/api/query/$type'
    | '/api/media/'
    | '/api/doc/$type/$id'
    | '/api/history/$type/$id'
    | '/api/media/$id/usage'
    | '/api/media/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HealthRoute: typeof HealthRoute
  LoginRoute: typeof LoginRoute
  ApiListenRoute: typeof ApiListenRoute
  ApiMutateRoute: typeof ApiMutateRoute
  ApiPresenceRoute: typeof ApiPresenceRoute
  ApiSchemasRoute: typeof ApiSchemasRoute
  DebugLiveRoute: typeof DebugLiveRoute
  StructureSplatRoute: typeof StructureSplatRoute
  StructureIndexRoute: typeof StructureIndexRoute
  ApiBacklinksIdRoute: typeof ApiBacklinksIdRoute
  ApiMediaUploadRoute: typeof ApiMediaUploadRoute
  ApiQueryTypeRoute: typeof ApiQueryTypeRoute
  ApiMediaIndexRoute: typeof ApiMediaIndexRoute
  ApiDocTypeIdRoute: typeof ApiDocTypeIdRoute
  ApiHistoryTypeIdRoute: typeof ApiHistoryTypeIdRoute
  ApiMediaIdUsageRoute: typeof ApiMediaIdUsageRoute
  ApiMediaIdIndexRoute: typeof ApiMediaIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/listen': {
      id: '/api/listen'
      path: '/api/listen'
      fullPath: '/api/listen'
      preLoaderRoute: typeof ApiListenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mutate': {
      id: '/api/mutate'
      path: '/api/mutate'
      fullPath: '/api/mutate'
      preLoaderRoute: typeof ApiMutateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/presence': {
      id: '/api/presence'
      path: '/api/presence'
      fullPath: '/api/presence'
      preLoaderRoute: typeof ApiPresenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/schemas': {
      id: '/api/schemas'
      path: '/api/schemas'
      fullPath: '/api/schemas'
      preLoaderRoute: typeof ApiSchemasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug/live': {
      id: '/debug/live'
      path: '/debug/live'
      fullPath: '/debug/live'
      preLoaderRoute: typeof DebugLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/structure/': {
      id: '/structure/'
      path: '/structure'
      fullPath: '/structure/'
      preLoaderRoute: typeof StructureIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/structure/$': {
      id: '/structure/$'
      path: '/structure/$'
      fullPath: '/structure/$'
      preLoaderRoute: typeof StructureSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/backlinks/$id': {
      id: '/api/backlinks/$id'
      path: '/api/backlinks/$id'
      fullPath: '/api/backlinks/$id'
      preLoaderRoute: typeof ApiBacklinksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/': {
      id: '/api/media/'
      path: '/api/media'
      fullPath: '/api/media/'
      preLoaderRoute: typeof ApiMediaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/upload': {
      id: '/api/media/upload'
      path: '/api/media/upload'
      fullPath: '/api/media/upload'
      preLoaderRoute: typeof ApiMediaUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/query/$type': {
      id: '/api/query/$type'
      path: '/api/query/$type'
      fullPath: '/api/query/$type'
      preLoaderRoute: typeof ApiQueryTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/doc/$type/$id': {
      id: '/api/doc/$type/$id'
      path: '/api/doc/$type/$id'
      fullPath: '/api/doc/$type/$id'
      preLoaderRoute: typeof ApiDocTypeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/history/$type/$id': {
      id: '/api/history/$type/$id'
      path: '/api/history/$type/$id'
      fullPath: '/api/history/$type/$id'
      preLoaderRoute: typeof ApiHistoryTypeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/$id/': {
      id: '/api/media/$id/'
      path: '/api/media/$id'
      fullPath: '/api/media/$id/'
      preLoaderRoute: typeof ApiMediaIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/$id/usage': {
      id: '/api/media/$id/usage'
      path: '/api/media/$id/usage'
      fullPath: '/api/media/$id/usage'
      preLoaderRoute: typeof ApiMediaIdUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HealthRoute: HealthRoute,
  LoginRoute: LoginRoute,
  ApiListenRoute: ApiListenRoute,
  ApiMutateRoute: ApiMutateRoute,
  ApiPresenceRoute: ApiPresenceRoute,
  ApiSchemasRoute: ApiSchemasRoute,
  DebugLiveRoute: DebugLiveRoute,
  StructureSplatRoute: StructureSplatRoute,
  StructureIndexRoute: StructureIndexRoute,
  ApiBacklinksIdRoute: ApiBacklinksIdRoute,
  ApiMediaUploadRoute: ApiMediaUploadRoute,
  ApiQueryTypeRoute: ApiQueryTypeRoute,
  ApiMediaIndexRoute: ApiMediaIndexRoute,
  ApiDocTypeIdRoute: ApiDocTypeIdRoute,
  ApiHistoryTypeIdRoute: ApiHistoryTypeIdRoute,
  ApiMediaIdUsageRoute: ApiMediaIdUsageRoute,
  ApiMediaIdIndexRoute: ApiMediaIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
